import { type AppProps, type AppType } from "next/app";
import { type Session } from "next-auth";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { SessionProvider } from "next-auth/react";

import { api } from "~/utils/api";

import "~/styles/globals.css";
import { type ReactElement, type ReactNode, useState } from "react";
import Head from "next/head";
import { type NextPage } from "next";
import setLayoutDefinitions from "~/components/_setLayoutDefinitions";
import { Toaster } from "react-hot-toast";
import { useTheme } from "~/hooks/useTheme";

export type NextPageWithLayout = NextPage & {
	getLayout?: (page: ReactElement) => ReactNode;
};

type AppPropsWithLayout = AppProps<{ session: Session | null }> & {
	Component: NextPageWithLayout;
};

const MyApp: AppType<{ session: Session | null }> = ({
	Component,
	pageProps: { session, ...pageProps },
}: AppPropsWithLayout) => {
	useTheme();

	const [queryClient] = useState(
		() =>
			new QueryClient({
				defaultOptions: { queries: { refetchOnWindowFocus: true } },
			})
	);

	setLayoutDefinitions();

	const getLayout = Component.getLayout ?? (page => page);

	return (
		<>
			<Head>
				<title>Hiluna Shop</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Toaster />

			<SessionProvider session={session}>
				<QueryClientProvider client={queryClient}>
					{getLayout(<Component {...pageProps} />)}
				</QueryClientProvider>
			</SessionProvider>
		</>

	);
};

export default api.withTRPC(MyApp);
