import { type AppProps, type AppType } from "next/app";
import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";

import { api } from "~/utils/api";

import "~/styles/globals.css";
import { type ReactElement, type ReactNode } from "react";
import Head from "next/head";
import { type NextPage } from "next";
import setLayoutDefinitions from "~/components/_setLayoutDefinitions";
import { Toaster } from "react-hot-toast";
import { useTheme } from "~/hooks/useTheme";

export type NextPageWithLayout = NextPage & {
	getLayout?: (page: ReactElement) => ReactNode;
};

type AppPropsWithLayout = AppProps<{ session: Session | null }> & {
	Component: NextPageWithLayout;
};

const MyApp: AppType<{ session: Session | null }> = ({
	Component,
	pageProps: { session, ...pageProps },
}: AppPropsWithLayout) => {
	useTheme();

	setLayoutDefinitions();

	const getLayout = Component.getLayout ?? (page => page);

	return (
		<>
			<Head>
				<title>Hiluna Shop</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
				<meta name="theme-color" media="(prefers-color-scheme: light)" content="#7BA8D4" />
			</Head>

			<Toaster />

			<SessionProvider session={session}>
				{getLayout(<Component {...pageProps} />)}
			</SessionProvider>
		</>
	);
};

export default api.withTRPC(MyApp);
